name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v2

        with:
          path: .
          node-version: 24
          package-manager: pnpm
